version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_ans
    environment:
      POSTGRES_USER: user_ans
      POSTGRES_PASSWORD: password_ans
      POSTGRES_DB: ans_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

